### PR TITLE
Warning note about JLD security

### PR DESCRIPTION
**Pull request by MikeInnes**
This seems worth mentioning.

### CODE REVIEW

**Comment by simonster** [comment]
I think we should say "may be capable" instead of "are capable." I don't think we want this to be possible and we should fix it if we can. There are some safeguards in the code, but no one has validated the safeguards, so it would not surprise me if they are insufficient.

**Comment by MikeInnes** [comment]
In the current state of things, "are capable":
```julia
julia> JLD._julia_type("TypeVar(println(\"you got pwned\"))")
you got pwned
you got pwned
JLD.UnsupportedType
```

Interesting that it prints twice...

This code can't really be safe unless it takes a more principled approach to serialising types than print/parse/eval. That approach is the source of other problems too, like limitations on what identifier names

**Comment by simonster** [comment]
The code should be checking that the arguments to `TypeVar`, `Union`, etc. also satisfy `is_valid_type_ex`, which would fix that particular case. But I agree with you that the entire strategy is wrong. There are lots of corner cases where calling `eval` can execute code, and catching all of these is difficult. We should actually serialize the types using JLD itself. This is [what JLD2 does](https://github.com/simonster/JLD2.jl/blob/master/src/data.jl#L1039-L1114).

**Comment by MikeInnes** [comment]
Great, I agree that's the right approach and it's great to hear things will be moving in the right direction. Is JLD2 stable in any way yet? Should I add a mention of that package to this note?

**Comment by simonster** [comment]
JLD does not work with Julia >0.4, and I'm not sure if I'll ever have time to finish it.

**Comment by MikeInnes** [comment]
Thanks 👍

**Pull request merged**
