### PR TITLE
Adjust test of StackFrame serialization to work on 32 bit platforms

### PR DESCRIPTION
**Pull request by andreasnoack**
I don't have a 32 bit installation so I'm now sure if this works. Let's see what AppVeyor says.

### CODE REVIEW

**Comment by musm** [comment]
backed up log at https://gist.github.com/musm/07238448f01c0970967603b5a9929264
restarting ci

**Comment by andreasnoack** [comment]
I suspect that size of the unsigned integer has changed from 0.5 to 0.6. I also don't see the Linux error locally. Unfortunately, I don't have time to look more into this right now but might return to it in a couple of weeks unless somebody else beats me to it.

**Comment by musm** [comment]
I'm not sure with master 32 bit julia is failing on appveyor, the travis on master have never passed in recent times due to problems with JLDArchive.

I think this PR is good to go

**Comment by musm** [comment]
I dont think this has anything to do with the size of unsized integers from 0.5 to 0.6 as that has not changed i.e. `UInt is UInt32` on 32 bit system and that has not changed

**Comment by tkelman** [comment]
This is not correct. From Base: `base/profile.jl:76:const LineInfoDict = Dict{UInt64, Vector{StackFrame}}`

**Comment by musm** [comment]
Hmm strange, since I'm getting
```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  i686-w64-mingw32

julia> @profile eigvals(randn(3,3))
3-element Array{Complex{Float64},1}:
 -1.32646+0.671433im
 -1.32646-0.671433im
  1.14593+0.0im

julia> li, lidict = Profile.retrieve()
(UInt32[0x6b89b221,0x76dd70f4,0x6bf68495,0x6b6b29dc,0x6bf6e4fd,0x77de2d7e,0x6b6b074d,0x6b7dbd6b,0x6b552b1b,0x76dd70d5  …  0x654539e0,0x2f4d33ef,0x2f4d34aa,0x6545392f,0x2f4d0b49,0x2f4d0e51,0x6545392f,0x65471775,0x00402034,0x00000000],Dict(0x654e0ff1=>StackFrame[ in operator() at functional:2439 [inlined], in addModuleSet<llvm::SmallVector<std::unique_ptr<llvm::Module>, 1u>, llvm::RTDyldMemoryManager*, std::unique_ptr<llvm::orc::LambdaResolver<JuliaOJIT::addModule(std::unique_ptr<llvm::Module>)::<lambda(const string&)>, JuliaOJIT::addModule(std::unique_ptr<llvm::Module>)::<lambda(const string&)> >, std::default_delete<llvm::orc::LambdaResolver<JuliaOJIT::addModule(std::unique_ptr<llvm::Module>)::<lambda(const string&)>, JuliaOJIT::addModule(std::unique_ptr<llvm::Module>)::<lambda(const string&)> > > > > at IRCompileLayer.h:76 [inlined], in addModule at jitlayers.cpp:521],0x6b7d7251=>StackFrame[ in ZN4llvm17PMTopLevelManager16findAnalysisPassEPKv at LLVM-3.7.dll:?],0x286d84b0=>StackFrame[ in ip:0x286d84af],0x6ba1933b=>StackFrame[ in ZN4llvm13AliasAnalysis13getModRefInfoENS_17ImmutableCallSiteERKNS_14MemoryLocationE at LLVM-3.7.dll:?],0x6bb0d7d9=>StackFrame[ in ZN4llvm18matchSelectPatternEPNS_5ValueERS1_S2_PNS_11Instruction7CastOpsE at LLVM-3.7.dll:?],0x6b7d8447=>StackFrame[ in ZN4llvm13PMDataManager16removeDeadPassesEPNS_4PassENS_9StringRefENS_19PassDebuggingStringE at LLVM-3.7.dll:?],0x6bbffda3=>StackFrame[ in ZN4llvm12SelectionDAG22AssignTopologicalOrderEv at LLVM-3.7.dll:?],0x6feb5fd5=>StackFrame[ in ZNSs4_Rep8_M_cloneERKSaIcEj at libstdc++-6.dll:?],0x6b32cb9f=>StackFrame[ in ZN4llvm12InstCombiner3runEv at LLVM-3.7.dll:?],0x6bc0a7cf=>StackFrame[ in ZN4llvm12SelectionDAG18ReplaceAllUsesWithENS_7SDValueES1_ at LLVM-3.7.dll:?]…))


```

**Comment by tkelman** [comment]
ah looks like that changed in ff0a6b390075c01f88f30347abb44acc7c30e277

**Comment by musm** [comment]
do you know how I can get the VersionNumber for that commit 60f20bd58c5ca59275b3fb18760dbbf9b9089ca8 https://github.com/JuliaLang/julia/commit/60f20bd58c5ca59275b3fb18760dbbf9b9089ca8 ?

**Comment by tkelman** [comment]
run contrib/commit-name.sh - v"0.6.0-dev.384"

**Comment by musm** [comment]
thanks

**Comment by musm** [comment]
submitted pr which will hopefully fix this https://github.com/JuliaIO/JLD.jl/pull/148

**Pull request merged**
