### PR TITLE
Bump minimum Julia version to 0.6

### PR DESCRIPTION
**Pull request by ararslan**
Much easier to maintain than trying to support 0.4, 0.5, 0.6, and 0.7 all at once. Plus some 0.7 depwarns require at least 0.6 to silence.

### CODE REVIEW

**Comment by ararslan** [comment]
There's an existing failure on 0.7 but now JLD tests are passing on 0.6. However, the JLDArchive tests are not, directly due to this change. (Though I guess they weren't passing before anyway?)

**Comment by ararslan** [comment]
Should we go ahead and merge this, then rebase Jameson's PR?

**Comment by simonster** [comment]
Fine with me, as long as I don't have to do the rebasing 😃 . Should also adjust JLDArchives, since it [currently tries to access JLD.TYPESYSTEM_06](https://github.com/JuliaIO/JLDArchives.jl/blob/2bd81889e72475cd79f64f3af4e5c03b10830cec/test/v0.2.jl#L51) which is removed by this patch.

**Comment by ararslan** [comment]
I can take care of the rebasing if you want to take care of JLDArchives 😉

**Pull request merged**
