### PR TITLE
RFC: Naive fix for Julia v0.5 UTF16String removal

### PR DESCRIPTION
**Pull request by jrevels**
Here's my novice attempt at fixing #81. I'm not familiar with JLD's internals, so for all I know this is a horrible way to go, but I didn't want to open such a simple issue without doing my due open source diligence 😛

### CODE REVIEW

**Comment by timholy** [comment]
You are too kind!! See also #82.

**Comment by jrevels** [comment]
Ah! I didn't see that, awesome. Feel free to close this, then.

**Comment by timholy** [comment]
Let's see how they both fare with CI. OSX will fail, needs https://github.com/JuliaLang/METADATA.jl/pull/5588.

**Comment by timholy** [comment]
Ah, it does look like mine has passed, so I will close this. (We have some tricky tests, using [JLDArchives](https://github.com/JuliaIO/JLDArchives.jl), that only run on Travis so wouldn't show up as failures in local testing.)

**Pull request closed without merging**
